using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Windows.Forms;
using Microsoft.Win32;
using WireSockUI.Extensions;
using WireSockUI.Forms;
using WireSockUI.Properties;

namespace WireSockUI
{
    internal static class Program
    {
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            if (!Directory.Exists(Global.MainFolder)) Directory.CreateDirectory(Global.MainFolder);
            if (!Directory.Exists(Global.ConfigsFolder)) Directory.CreateDirectory(Global.ConfigsFolder);

            if (!IsWireSockArchitectureSupported())
            {
                MessageBox.Show(Resources.AppUnsupportedArchMessage, Resources.AppNoWireSockTitle,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                Environment.Exit(1);
            }

            if (!IsWireSockInstalled())
            {
                MessageBox.Show(Resources.AppNoWireSockMessage, Resources.AppNoWireSockTitle, MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
                OpenBrowser(Resources.AppWireSockURL);

                Environment.Exit(1);
            }

#if WIRESOCKUI_ENABLE_UWP
            CheckVersion();
#endif

            Application.Run(new FrmMain());
        }

        private static void OpenBrowser(string url)
        {
            try
            {
                Process.Start(url);
            }
            catch
            {
            }
        }

        /// <summary>
        ///     Determine if this WireSockUI was generated by an automated build from a GitHub repository
        /// </summary>
        /// <returns>Assembly repository if set during build</returns>
        private static string GetRepository()
        {
            var assembly = Assembly.GetExecutingAssembly();

            foreach (var metadata in assembly.GetCustomAttributes<AssemblyMetadataAttribute>())
                if (string.Equals(metadata.Key, "Repository"))
                    return metadata.Value;

            return null;
        }

#if WIRESOCKUI_ENABLE_UWP
        /// <summary>
        ///     Compare the local product version against the latest GitHub repository release tag
        /// </summary>
        /// <remarks>If auto update is enabled, repository is known and there is a new version, open up a browser window.</remarks>
        private static void CheckVersion()
        {
            if (!Settings.Default.AutoUpdate) return;
        
            try
            {
                var repository = GetRepository();
        
                if (!string.IsNullOrWhiteSpace(repository))
                {
                    var currentVersion = new Version(Application.ProductVersion);
                    var latestVersion = GitHubExtensions.GetLatestRelease(repository);
        
                    if (currentVersion != null && latestVersion != null && latestVersion > currentVersion)
                    {
                        var dialogResult = MessageBox.Show(Resources.AppUpdateMessage, Resources.AppUpdateTitle, MessageBoxButtons.OKCancel,
                            MessageBoxIcon.Information);
        
                        if (dialogResult == DialogResult.OK)
                        {
                            OpenBrowser($"https://github.com/{repository}/releases");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // user possibly doesn't have internet
                
            }
        }
#endif

        /// <summary>
        ///     Determine if the WireSock library components are installed.
        /// </summary>
        /// <returns><c>true</c> if installed, otherwise <c>false</c></returns>
        private static bool IsWireSockInstalled()
        {
            using (var key = Registry.LocalMachine.OpenSubKey("SOFTWARE\\NTKernelResources\\WinpkFilterForVPNClient"))
            {
                if (key == null) return false;
                var wiresockLocation = key.GetValue("InstallLocation") + "bin\\wiresock-client.exe";

                // Add the directory containing the wgbooster.dll to the system's path if it is not added
                var installPath = key.GetValue("InstallLocation").ToString();
                var binPath = Path.Combine(installPath, "bin");

                var environmentPath = Environment.GetEnvironmentVariable("PATH");

                if (environmentPath == null || environmentPath.Contains(binPath))
                    return File.Exists(wiresockLocation);

                environmentPath = $"{binPath};{environmentPath}";
                Environment.SetEnvironmentVariable("PATH", environmentPath);

                return File.Exists(wiresockLocation);
            }
        }

        /// <summary>
        ///     Determine if running under a supported architecture.
        /// </summary>
        /// <remarks>
        ///     WireSock VPN Client's wgbooster.dll currently forces us to match the operating system's architecture. Under
        ///     normal circumstances this check always succeeds, but under a debugger AnyCPU builds may run as x86 or x64
        ///     processes, disregarding the host OS bitness.
        /// </remarks>
        /// <returns><c>true</c> if supported, otherwise <c>false</c></returns>
        private static bool IsWireSockArchitectureSupported()
        {
            return Environment.Is64BitOperatingSystem == Environment.Is64BitProcess;
        }
    }
}
